### ISSUE TITLE
__init__.py namespace error

### ISSUE THREAD

**Issue by Cole128** [robertlugg/easygui#121]
I downloaded easygui and put it in my site-packages folder. When I typed `import easygui` into IDLE I got this error:
`Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import easygui
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/easygui/__init__.py", line 3, in <module>
    __all__ = easygui.__all__
NameError: name 'easygui' is not defined`

So I went into the __init__.py and I think I found the error. In the first line it says `from easygui import *` which means that you don't have to put `easygui.` in front of easygui functions. But then in the third line it says `__all__ = easygui.__all__`
Python looks for easygui.__all__ when we don't have that namespace because of the way easygui was imported.
But when I change the first line to say `import easygui` python gives me the error that `module 'easygui' has no attribute '__all__'`
What's going on?

**Comment by zadacka** [comment]
Try using 'from easygui import *' instead of 'import easygui', and you 
should import everything.
Alternatively, use 'from easygui import <specific thing you want to 
import>' in order to keep your namespace clean.

Attributes like '__all__' are private and get name mangled. As a general 
rule of thumb you don't want to access things like that. You can still 
access private attributes if you really want.
Does that help?

**Comment by Cole128** [comment]
Ok thanks, but is there an issue with my fix?

**Comment by zadacka** [comment]
Short answer - use v0.98 from GitHub (here!) or from PIP. I'll update SourceForge to point people here. 
Longer answer - I'm curious about what wasn't working and how your fix works and want to look into it. When I get the chance I'll try to reproduce it and understand how this works.

**Comment by Cole128** [comment]
@zadacka 
Okay, but make sure to tell people to isolate the easygui folder from the .zip file that gets downloaded, it was a little confusing at first. Thanks!
