### ISSUE TITLE
button box msg getter throws error if message was not previously set.

### ISSUE THREAD

**Issue by spyoungtech** [robertlugg/easygui#151]
```
>>> box = eg.buttonbox('Test!', run=False)
>>> box.msg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\easygui\boxes\button_box.py", line 182, in msg
    return self._msg
AttributeError: 'ButtonBox' object has no attribute '_msg'
```

To avoid this, the `_msg` attribute should ideally be set in the BottonBox's `__init__`  method.

**Comment by zadacka** [comment]
@spyoungtech - yep, I'd agree with your assessent! I've got a work-in-progress refactor on a branch which would do this, but it is incomplete. If you'd like to submit a patch request for this specific change in the meantime we could get it in sooner? Alternatively we can leave this open until I get around to finishing the refactor and fixing this.
