### ISSUE TITLE
Does EasyGui depend on tkinter?

### ISSUE THREAD

**Issue by sceasary** [robertlugg/easygui#156]
easygui 98 - dependency on tkinter?

As I launched the example of easygui - I got an exception...

`import easygui
easygui.ynbox('Shall I continue?', 'Title', ('Yes', 'No'))` 

The exception 

`C:\Python27\python.exe C:/Users/shayc/Documents/TDK_Calib/dummy.py
Traceback (most recent call last):
  File "C:/Users/shayc/Documents/TDK_Calib/dummy.py", line 1, in <module>
    import easygui
  File "C:\Users\shayc\AppData\Roaming\Python\Python27\site-packages\easygui\__init__.py", line 34, in <module>
    from .boxes.button_box import buttonbox
  File "C:\Users\shayc\AppData\Roaming\Python\Python27\site-packages\easygui\boxes\button_box.py", line 19, in <module>
    import utils as ut
  File "C:\Users\shayc\AppData\Roaming\Python\Python27\site-packages\easygui\boxes\utils.py", line 43, in <module>
    raise ImportError("Unable to find tkinter package.")
ImportError: Unable to find tkinter package.

Process finished with exit code 1`

**Comment by spyoungtech** [comment]
Yes, easygui depends on Tk (tkinter) being available.
