### ISSUE TITLE
Arrow Keys Cause Enterbox to Return NoneType

### ISSUE THREAD

**Issue by jpfischbein** [robertlugg/easygui#170]
When using an enterbox(), if the user uses arrow keys to navigate the text within the text field, an AttributeError is thrown and the return is NoneType. Stacktrace:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\easygui\boxes\base_boxes.py", line 27, in tabLeft
    boxRoot.event_generate("<Shift-Tab>")
AttributeError: 'NoneType' object has no attribute 'event_generate'
```

**Comment by CheongKoo** [comment]
I am getting the same error on my Windows PC running python. All the arrow keys still work in the text box except for the exception being thrown whenever I press the arrow keys.
Thank you.

**Comment by wbrearle** [comment]
I also am seeing this error.  Is there a fix out somewhere?  Or at least a way to suppress this error message?

**Comment by tomhea** [comment]
Hi! I think I found a solution to it (PR #222).
@zadacka
