### ISSUE TITLE
Exception when cancelling fileopenbox

### ISSUE THREAD

**Issue by rbalik** [robertlugg/easygui#87]
If I hit cancel on a fileopenbox I get the following exception:
```
Traceback (most recent call last):
  File "./dashupdater.py", line 139, in update
    self.start_update(ui)
  File "./dashupdater.py", line 126, in start_update
    self.imagefile = ui.prompt_for_file()
  File "/home/rbalik/firmware/Releases/updater/libs/updatergui.py", line 80, in prompt_for_file
    title=self.title)
  File "/usr/local/lib/python2.7/dist-packages/easygui/boxes/base_boxes.py", line 898, in fileopenbox
    f = os.path.normpath(ret_val)
  File "/usr/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'tuple' object has no attribute 'startswith'
```

**Comment by robertlugg** [comment]
There are a large number of changes in 'develop' that are long overdue to be merged into the master branch.  I'll do that in the next couple of days.  In the develop branch, I did not see this problem.  If it still exists after the integration I'll look into it.

**Comment by robertlugg** [comment]
I integrated develop into master.  I don't see the issue, however I did put a 'try' around that command.  If you would, try it again.  Please reopen if you get the error again.  Thanks for reporting.

**Comment by rbalik** [comment]
I think this might still be an issue. I updated to 0.97.4 via pip and I still get the exception:

```
---
Name: easygui
Version: 0.97.4
Location: /home/rbalik/.local/lib/python2.7/site-packages
Requires: 
```

```
Traceback (most recent call last):
  File "./dashupdater.py", line 144, in update
    self.start_update(ui)
  File "./dashupdater.py", line 131, in start_update
    self.imagefile = ui.prompt_for_file()
  File "/home/rbalik/firmware/Releases/updater/libs/updatergui.py", line 85, in prompt_for_file
    title=self.title)
  File "/home/rbalik/.local/lib/python2.7/site-packages/easygui/boxes/base_boxes.py", line 898, in fileopenbox
    f = os.path.normpath(ret_val)
  File "/usr/lib/python2.7/posixpath.py", line 335, in normpath
    initial_slashes = path.startswith('/')
AttributeError: 'tuple' object has no attribute 'startswith'
```

**Comment by robertlugg** [comment]
The changes I made are only available here on github.  I haven't pushed 0.98.0 to pypi yet.

**Comment by orestisf1993** [comment]
This is still an issue for me with 0.98.0:

```
$ pip show easygui
---
Metadata-Version: 1.1
Name: easygui
Version: 0.98.0-UNRELEASED
```
After pressing cancel in the menu:
```
...
    filename = easygui.fileopenbox(msg="Enter PGN file with the game.", filetypes=["*.pgn"])
  File "/usr/lib/python3.5/site-packages/easygui/boxes/fileopen_box.py", line 118, in fileopenbox
    raise e
  File "/usr/lib/python3.5/site-packages/easygui/boxes/fileopen_box.py", line 115, in fileopenbox
    f = os.path.normpath(ret_val)
  File "/usr/lib/python3.5/posixpath.py", line 332, in normpath
    initial_slashes = path.startswith(sep)
AttributeError: 'tuple' object has no attribute 'startswith'
```

**Comment by rbalik** [comment]
It looks like the issue is with this code in fileopen_box:

```
        try:
            f = os.path.normpath(ret_val)
        except AttributeError as e:
            print("ret_val is {}".format(ret_val))
            raise e
```

You pass the ret_val directly into normpath without checking to see what it is and you do catch the exception, but then you raise it again.
