### ISSUE TITLE
fileopenbox() throws AttributeError

### ISSUE THREAD

**Issue by LiaungYip** [robertlugg/easygui#95]
Using:

* latest `easygui` (cloned from GitHub)
* Python 2.7.11 on win32
* `Tkinter.TkVersion -> 8.5`

... attempting to execute `easygui.fileopenbox()` throws an `AttributeError`.

    C:\tools\python2\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.1.2\helpers\pydev\pydevconsole.py" 58912 58913
    PyDev console: starting.
    
    import sys; print('Python %s on %s' % (sys.version, sys.platform))
    sys.path.extend(['C:\\Users\\layip\\git\\ptw_python'])
    
    Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
    >>> import easygui
    >>> easygui.fileopenbox()
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "C:\tools\python2\lib\site-packages\easygui-0.98.0-py2.7.egg\easygui\boxes\fileopen_box.py", line 103, in fileopenbox
    	func = ut.tk_FileDialog.askopenfilenames if multiple else ut.tk_FileDialog.askopenfilename
    AttributeError: 'module' object has no attribute 'askopenfilename'
    

I set a breakpoint at `fileopen_box.py:103` and inspected the `ut` and `tk_FileDialog` variables:

    >>> ut
    <module 'easygui.boxes.utils' from 'C:\tools\python2\lib\site-packages\easygui-0.98.0-py2.7.egg\easygui\boxes\utils.pyc'>
    >>> ut.tk_FileDialog
    <module 'tkinter.filedialog' from 'C:\tools\python2\lib\site-packages\tkinter\filedialog.pyc'>

Strangely if I import the `tkFileDialog` module directly, it works fine:

    >>> import tkFileDialog
    >>> tkFileDialog.askopenfilename()
    u'C:/Users/layip/test.txt'

Even more strangely, the `tkFileDialog` imported is a different file to `ut.tk_FileDialog`:

    >>> import tkFileDialog
    >>> tkFileDialog
    <module 'tkFileDialog' from 'C:\tools\python2\lib\lib-tk\tkFileDialog.py'>

**Comment by LiaungYip** [comment]
This was a local environment issue.

Somehow, another module named `tkinter` was installed in `C:\tools\python2\lib\site-packages\tkinter\`, shadowing the actual one in `C:\tools\python2\lib\lib-tk\`.

Deleting `C:\tools\python2\lib\site-packages\tkinter\` solved the issue.
