### ISSUE TITLE
syntax error in 0.98 choice_box

### ISSUE THREAD

**Issue by nelizzzz** [robertlugg/easygui#97]
after manually updating from 0.97.4 to 0.98 (Anaconda, Python 3):

```
>>> import easygui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\easygui\__init__.py", line 50, in <module>
    from .boxes.choice_box import choicebox
  File "C:\Anaconda3\lib\site-packages\easygui\boxes\choice_box.py", line 76
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by damonlynch** [comment]
Confirming this bug on Python 3. That style of exception syntax has been deprecated for 8 years now on Python 2.6 / 2.7, and has never been valid Python 3.x syntax.

See https://docs.python.org/dev/whatsnew/2.6.html#pep-3110-exception-handling-changes

**Comment by pletnes** [comment]
This is the commit and code in question. Ran into the same issue myself.

https://github.com/robertlugg/easygui/commit/b5eab34c021d1d6eb5e51b67b81da6dbee56e94a#commitcomment-17946353

**Comment by tryeverything** [comment]
replace , with as . 
Please fix the bug

**Comment by FlyingLotus1983** [comment]
@kaselis has graciously submitted a pull request 15 days ago that will fix this:

#100 - Python 3 invalid syntax error

Being that easygui is currently 100% broken for python 3.5 after being downloaded from pip,  I'm asking the authors / admins of this repo to take a minute and merge this pull request in, so those of us using it in production don't have to go around and manually install an older version from pip ... I'll buy you guys a beer one day :+1:

**Comment by zadacka** [comment]
Right, that does sound like a problem.

Robert, would you be able to test and merge in the pull request please?
Once that's done I'll push out the updated version to PyPi so that the PIP
install will work...

Thanks,
